# Generated by Django 5.2.1 on 2025-05-21 21:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MuscleGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Grupo muscular',
                'verbose_name_plural': 'Grupos musculares',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('use_weight', models.BooleanField(default=False)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('tip', models.TextField()),
                ('photo', models.ImageField(upload_to='exercises/')),
                ('video_url', models.URLField(blank=True)),
                ('reps', models.PositiveIntegerField(default=0)),
                ('sets', models.PositiveIntegerField(default=0)),
                ('rest_sec', models.PositiveIntegerField(default=60)),
                ('muscles', models.ManyToManyField(related_name='exercises', to='app_academia.musclegroup')),
                ('tags', models.ManyToManyField(related_name='exercises', to='app_academia.tag')),
            ],
            options={
                'verbose_name': 'Exercício',
                'verbose_name_plural': 'Exercícios',
            },
        ),
        migrations.CreateModel(
            name='TrainingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('difficulty', models.CharField(choices=[('beginner', 'Iniciante'), ('intermediate', 'Intermediário'), ('advanced', 'Avançado')], max_length=20)),
                ('days_count', models.PositiveSmallIntegerField(default=1)),
                ('is_template', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Plano de treino',
                'verbose_name_plural': 'Planos de treino',
            },
        ),
        migrations.CreateModel(
            name='PlanDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveSmallIntegerField()),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_academia.trainingplan')),
            ],
            options={
                'verbose_name': 'Dia do plano de treino',
                'verbose_name_plural': 'Dias do plano de treino',
            },
        ),
        migrations.CreateModel(
            name='ActivePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_academia.trainingplan')),
            ],
            options={
                'verbose_name': 'Plano de treino ativo',
                'verbose_name_plural': 'Planos de treino ativos',
            },
        ),
        migrations.CreateModel(
            name='CustomPlan',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('app_academia.trainingplan',),
        ),
        migrations.CreateModel(
            name='WorkoutDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('tags', models.ManyToManyField(blank=True, to='app_academia.tag')),
            ],
            options={
                'verbose_name': 'Dia de treino',
                'verbose_name_plural': 'Dias de treino',
            },
        ),
        migrations.AddField(
            model_name='trainingplan',
            name='days',
            field=models.ManyToManyField(related_name='training_plans', through='app_academia.PlanDay', to='app_academia.workoutday'),
        ),
        migrations.AddField(
            model_name='planday',
            name='day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_academia.workoutday'),
        ),
        migrations.CreateModel(
            name='WorkoutDayExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('custom_reps', models.PositiveIntegerField(blank=True, null=True)),
                ('custom_sets', models.PositiveIntegerField(blank=True, null=True)),
                ('rest_sec', models.PositiveIntegerField(blank=True, null=True)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_academia.workoutday')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_academia.exercise')),
            ],
            options={
                'verbose_name': 'Exercício do dia de treino',
                'verbose_name_plural': 'Exercícios do dia de treino',
            },
        ),
        migrations.AddField(
            model_name='workoutday',
            name='exercises',
            field=models.ManyToManyField(related_name='workout_days', through='app_academia.WorkoutDayExercise', to='app_academia.exercise'),
        ),
        migrations.CreateModel(
            name='WorkoutSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('feeling', models.CharField(choices=[('easy', 'Fácil'), ('hard', 'Difícil'), ('tired', 'Cansativo')], max_length=20)),
                ('completed', models.BooleanField(default=False)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_academia.workoutday')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sessão de treino',
                'verbose_name_plural': 'Sessões de treino',
            },
        ),
    ]
