# Generated by Django 5.2.1 on 2025-05-21 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_academia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='photo',
            field=models.ImageField(upload_to='exercises/photos/'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='tip',
            field=models.TextField(),
        ),
    ]
