# Generated by Django 5.2.1 on 2025-05-22 16:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_academia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutsession',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
