# Generated by Django 5.2.1 on 2025-05-21 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_academia', '0002_alter_exercise_description_alter_exercise_photo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activeplan',
            options={'verbose_name': 'Plano de treino ativo', 'verbose_name_plural': 'Planos de treino ativos'},
        ),
        migrations.AlterModelOptions(
            name='exercise',
            options={'verbose_name': 'Exercício', 'verbose_name_plural': 'Exercícios'},
        ),
        migrations.AlterModelOptions(
            name='musclegroup',
            options={'verbose_name': 'Grupo muscular', 'verbose_name_plural': 'Grupos musculares'},
        ),
        migrations.AlterModelOptions(
            name='planday',
            options={'verbose_name': 'Dia do plano de treino', 'verbose_name_plural': 'Dias do plano de treino'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Tag', 'verbose_name_plural': 'Tags'},
        ),
        migrations.AlterModelOptions(
            name='trainingplan',
            options={'verbose_name': 'Plano de treino', 'verbose_name_plural': 'Planos de treino'},
        ),
        migrations.AlterModelOptions(
            name='workoutday',
            options={'verbose_name': 'Dia de treino', 'verbose_name_plural': 'Dias de treino'},
        ),
        migrations.AlterModelOptions(
            name='workoutdayexercise',
            options={'verbose_name': 'Exercício do dia de treino', 'verbose_name_plural': 'Exercícios do dia de treino'},
        ),
        migrations.AlterModelOptions(
            name='workoutsession',
            options={'verbose_name': 'Sessão de treino', 'verbose_name_plural': 'Sessões de treino'},
        ),
        migrations.AlterField(
            model_name='exercise',
            name='photo',
            field=models.ImageField(upload_to='media/exercises/photos/'),
        ),
    ]
