# Generated by Django 5.2.1 on 2025-05-22 19:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_academia', '0002_alter_workoutsession_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='activeplan',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de fim'),
        ),
        migrations.AlterField(
            model_name='activeplan',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Está ativo?'),
        ),
        migrations.AlterField(
            model_name='activeplan',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_academia.trainingplan', verbose_name='Plano de treino'),
        ),
        migrations.AlterField(
            model_name='activeplan',
            name='start_date',
            field=models.DateField(auto_now_add=True, verbose_name='Data de inicio'),
        ),
        migrations.AlterField(
            model_name='activeplan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='description',
            field=models.TextField(verbose_name='Descrição do exercício'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='muscles',
            field=models.ManyToManyField(related_name='exercises', to='app_academia.musclegroup', verbose_name='Grupos musculares afetados'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nome do exercício'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='photo',
            field=models.ImageField(upload_to='exercises/', verbose_name='Foto/gif do exercício'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='reps',
            field=models.PositiveIntegerField(default=0, verbose_name='Repetições'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='rest_sec',
            field=models.PositiveIntegerField(default=60, verbose_name='Descanso'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='sets',
            field=models.PositiveIntegerField(default=0, verbose_name='Séries'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='tags',
            field=models.ManyToManyField(related_name='exercises', to='app_academia.tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='tip',
            field=models.TextField(verbose_name='Dica'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='use_weight',
            field=models.BooleanField(default=False, verbose_name='Usa peso?'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='video_url',
            field=models.URLField(blank=True, verbose_name='URL do video'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Peso'),
        ),
        migrations.AlterField(
            model_name='musclegroup',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Nome do grupo muscular'),
        ),
        migrations.AlterField(
            model_name='planday',
            name='day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_academia.workoutday', verbose_name='Dia de treino'),
        ),
        migrations.AlterField(
            model_name='planday',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_academia.trainingplan', verbose_name='Plano de treino'),
        ),
        migrations.AlterField(
            model_name='planday',
            name='sequence',
            field=models.PositiveSmallIntegerField(verbose_name='Ordem'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=20, unique=True, verbose_name='Nome da tag'),
        ),
        migrations.AlterField(
            model_name='trainingplan',
            name='days',
            field=models.ManyToManyField(related_name='training_plans', through='app_academia.PlanDay', to='app_academia.workoutday', verbose_name='Dias'),
        ),
        migrations.AlterField(
            model_name='trainingplan',
            name='days_count',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Quantidade de dias'),
        ),
        migrations.AlterField(
            model_name='trainingplan',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descrição do plano de treino'),
        ),
        migrations.AlterField(
            model_name='trainingplan',
            name='difficulty',
            field=models.CharField(choices=[('beginner', 'Iniciante'), ('intermediate', 'Intermediário'), ('advanced', 'Avançado')], max_length=20, verbose_name='Dificuldade'),
        ),
        migrations.AlterField(
            model_name='trainingplan',
            name='is_template',
            field=models.BooleanField(default=True, verbose_name='É um template?'),
        ),
        migrations.AlterField(
            model_name='trainingplan',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nome do plano de treino'),
        ),
        migrations.AlterField(
            model_name='trainingplan',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Criador'),
        ),
        migrations.AlterField(
            model_name='workoutday',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descrição do dia de treino'),
        ),
        migrations.AlterField(
            model_name='workoutday',
            name='exercises',
            field=models.ManyToManyField(related_name='workout_days', through='app_academia.WorkoutDayExercise', to='app_academia.exercise', verbose_name='Exercícios'),
        ),
        migrations.AlterField(
            model_name='workoutday',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nome do dia de treino'),
        ),
        migrations.AlterField(
            model_name='workoutday',
            name='tags',
            field=models.ManyToManyField(blank=True, to='app_academia.tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='workoutdayexercise',
            name='custom_reps',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Repetições'),
        ),
        migrations.AlterField(
            model_name='workoutdayexercise',
            name='custom_sets',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Séries'),
        ),
        migrations.AlterField(
            model_name='workoutdayexercise',
            name='day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_academia.workoutday', verbose_name='Dia de treino'),
        ),
        migrations.AlterField(
            model_name='workoutdayexercise',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_academia.exercise', verbose_name='Exercício'),
        ),
        migrations.AlterField(
            model_name='workoutdayexercise',
            name='order',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Ordem'),
        ),
        migrations.AlterField(
            model_name='workoutdayexercise',
            name='rest_sec',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Descanso'),
        ),
        migrations.AlterField(
            model_name='workoutsession',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='workoutsession',
            name='day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_academia.workoutday', verbose_name='Dia de treino'),
        ),
        migrations.AlterField(
            model_name='workoutsession',
            name='duration',
            field=models.DurationField(blank=True, null=True, verbose_name='Duração'),
        ),
        migrations.AlterField(
            model_name='workoutsession',
            name='feeling',
            field=models.CharField(choices=[('easy', 'Fácil'), ('normal', 'Normal'), ('hard', 'Difícil'), ('tired', 'Cansativo')], max_length=20, verbose_name='Como foi o treino?'),
        ),
        migrations.AlterField(
            model_name='workoutsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
    ]
